const bodies = {
  spring: [
    "Antlia",
    "Corvus",
    "Lynx",
    "Boötes",
    "Crater",
    "Musca",
    "Cancer",
    "Crux",
    "Pyxis",
    "Canes Venatici",
    "Hydra",
    "Sextans",
    "Centaurus",
    "Leo",
    "Ursa Major",
    "Chamaeleon",
    "Leo Minor",
    "Ursa Minor",
    "Coma Berenices",
    "Lupus",
    "Virgo",
  ],
  summer: [
    "Apus",
    "Draco",
    "Pavo",
    "Aquila",
    "Equuleus",
    "Sagitta",
    "Ara",
    "Hercules",
    "Sagittarius",
    "Capricornus",
    "Indus",
    "Scorpius",
    "Circinus",
    "Libra",
    "Scutum",
    "Corona Australis",
    "Lyra",
    "Serpens",
    "Corona Borealis",
    "Microscopium",
    "Telescopium",
    "Cygnus",
    "Norma",
    "Triangulum Australe",
    "Delphinus",
    "Ophiuchus",
    "Vulpecula",
  ],
  fall: [
    "Andromeda",
    "Grus",
    "Pisces",
    "Aquarius",
    "Lacerta",
    "Piscis Austrinus",
    "Aries",
    "Octans",
    "Sculptor",
    "Cassiopeia",
    "Pegasus",
    "Triangulum",
    "Cepheus",
    "Perseus",
    "Tucana",
    "Cetus",
    "Phoenix",
  ],
  winter: [
    "Auriga",
    "Eridanus",
    "Orion",
    "Caelum",
    "Fornax",
    "Pictor",
    "Camelopardalis",
    "Gemini",
    "Puppis",
    "Canis Major",
    "Horologium",
    "Reticulum",
    "Canis Minor",
    "Hydrus",
    "Taurus",
    "Carina",
    "Lepus",
    "Vela",
    "Columba",
    "Mensa",
    "Volans",
    "Dorado",
    "Monoceros",
  ],
  planets: [
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
  ],
};

export default bodies;
